development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: mymac
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: myflix_test
  pool: 5
  username: mymac
  password:
